project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - src/user_guide.qmd

website:
  title: "Fuzzy address matcher"
  page-navigation: true
  back-to-top-navigation: true
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: src/user_guide.qmd
        text: User guide

format:
  html:
    theme: cosmo
